apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: coolcatclub-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: coolcatclub
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50 # scaling down to max 50% of pods at once
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100 # scaling down to max 50% of pods at once
        periodSeconds: 15
      - type: Pods
        value: 2 #or add 2 pods at once
        periodSeconds: 15
      selectPolicy: max

